name: DevOps CLI CLI
on:
  push:
    branches:["main"]

jobs:
  test-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      -name: Set up python
        uses: actions/setup-python@v5
        with:
         python-version: "3.13.7"

      -name: Install dependencies
        run: pip install requirements

      -name: Run list command
        run: python main.py list

      -name: Run api check
        run: python main.py api https://api.github.com